FROM google/golang-runtime

ENV INFLUXDB_PROTO http
ENV INFLUXDB_HOST $INFLUXDB_PORT_8086_TCP_ADDR
ENV INFLUXDB_PORT $INFLUXDB_PORT_8086_TCP_PORT
ENV INFLUXDB_NAME ircalyzer
ENV INFLUXDB_USER root
ENV INFLUXDB_PASS root

ENV IRC_SERVER irc.freenode.net:6667
ENV IRC_NICK ircalyzer
ENV IRC_CHANNEL #typo3-coreteam
