# Requires additional Python modules:
#
#   sudo pip install dopy passlib
#

- name: Deploy public key
  digital_ocean: >
    state=present
    command=ssh
    name="{{ do_ssh_key_name }}"
    ssh_pub_key="{{ my_pub_key }}"
  register: do_droplet

- name: Create / get Digital Ocean droplet 512Mb / Amsterdam 2 / Docker 1.3.0 on 14.04
  digital_ocean: >   
    state=present
    command=droplet
    id="{{ do_id }}"
    name="{{ do_hostname }}"
    size_id=66
    ssh_key_ids="{{ do_droplet.ssh_key.id }}"
    region_id=5
    image_id=6882330
    wait_timeout=600
  register: do_droplet

- debug: msg="ID is {{ do_droplet.droplet.id }}"
- debug: msg="IP is {{ do_droplet.droplet.ip_address }}"
    
- name: Add new droplet to inventory
  add_host: >
    name="{{ do_droplet.droplet.ip_address }}"
    groups=droplets
